apiVersion: nuclio.io/v1beta1
kind: Function
metadata:
  name: topsoil-pipe-http-trigger
  namespace: fast-platform
  labels:
    platform: fast
    module: core
    data: topsoil
spec:
  alias: latest
  description: Forge a download command from an http POST request
  handler: main:handler
  image: eufast/topsoil-pipe-http-trigger:0.1.0
  replicas: 1
  maxReplicas: 3
  targetCPU: 80
  runtime: python:3.6
  env:
  - name: KAFKA_BOOTSTRAP_SERVER
    value: "kafka-broker.kafka:9092"
  - name: TARGET_TOPIC
    value: topsoil-pipe-download
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      cpu: 1
      memory: 1Gi 
  triggers:
    http:
      attributes:
        ingresses:
          "dev":
            host: api.fast.sobloo.io
            paths:
            - /v1/fast/data/topsoil
      annotations:
        ingress.kubernetes.io/auth-secret: fast-ingress-auth
        ingress.kubernetes.io/auth-type: basic
      kind: http
      maxWorkers: 5
  version: -1
status:
  state: waitingForResourceConfiguration
